# Generated by Django 4.1.2 on 2022-10-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="reviews",
        ),
    ]
