# Generated by Django 4.1.2 on 2022-10-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_reviews"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="reviews",
        ),
    ]
